### ISSUE TITLE
[BUG] - Breaking Menu - Unhandled Exception (only happens sometimes)

### ISSUE THREAD

**Issue by Nikolai558** [Nikolai558/FE-BUDDY#41]
**Describe the bug**
Unhandled exception sometimes happens when the program completes.

```
************** Exception Text **************
System.ArgumentException: Parameter is not valid.
   at System.Drawing.FontFamily.GetName(Int32 language)
   at System.Drawing.FontFamily.get_Name()
   at System.Windows.Forms.FontCache.Data.FromFont(Font font, QUALITY quality)
   at System.Windows.Forms.FontCache.Data..ctor(Font font, QUALITY quality)
   at System.Windows.Forms.FontCache.CreateEntry(ValueTuple`2 key, Boolean cached)
   at System.Windows.Forms.RefCountedCache`3.<GetEntry>g__Add|8_1(TKey key)
   at System.Windows.Forms.RefCountedCache`3.GetEntry(TKey key)
   at System.Windows.Forms.FontCache.GetEntry(ValueTuple`2 key)
   at System.Windows.Forms.TextRenderer.DrawTextInternal(HDC hdc, ReadOnlySpan`1 text, Font font, Rectangle bounds, Color foreColor, QUALITY fontQuality, Color backColor, TextFormatFlags flags)
   at System.Windows.Forms.TextRenderer.DrawTextInternal(IDeviceContext dc, ReadOnlySpan`1 text, Font font, Rectangle bounds, Color foreColor, Color backColor, TextFormatFlags flags)
   at System.Windows.Forms.TextRenderer.DrawText(IDeviceContext dc, String text, Font font, Rectangle bounds, Color foreColor, TextFormatFlags flags)
   at System.Windows.Forms.ToolStripRenderer.OnRenderItemText(ToolStripItemTextRenderEventArgs e)
   at System.Windows.Forms.ToolStripProfessionalRenderer.OnRenderItemText(ToolStripItemTextRenderEventArgs e)
   at System.Windows.Forms.ToolStripRenderer.DrawItemText(ToolStripItemTextRenderEventArgs e)
   at System.Windows.Forms.ToolStripMenuItem.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.ToolStripItem.HandlePaint(PaintEventArgs e)
   at System.Windows.Forms.ToolStripItem.FireEvent(EventArgs e, ToolStripItemEventType met)
   at System.Windows.Forms.ToolStrip.OnPaint(PaintEventArgs e)
   at System.Windows.Forms.Control.PaintWithErrorHandling(PaintEventArgs e, Int16 layer)
   at System.Windows.Forms.Control.WmPaint(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Screenshots**
![image](https://user-images.githubusercontent.com/38259407/162602519-561f87b4-16e4-4049-a907-036d3bc06f89.png)

**Comment by Nikolai558** [comment]
I think what is happening here is that GC (Garbage Collection) is happening to soon on the PrivateFontCollection used for the menu fonts. This would only happen if the user does not have the "Romantic" font installed on their computer (I think).

I believe that I have fixed this error by making it a read-only variable that gets initialized when the form first loads up.
